### ISSUE TITLE
Border around `<body>` doesn't always cover whole page

### ISSUE THREAD

**Issue by danielhertenstein** [erikrose/gecko-dev#8]
Putting a border around the `<body>` doesn't create a border around the entire page sometimes. Two examples are walmart.com and wikipedia.org (see below).

![walmart](https://user-images.githubusercontent.com/5586735/70452692-93b79800-1a75-11ea-8e55-3c08d4c20608.png)
![wikipedia](https://user-images.githubusercontent.com/5586735/70452696-94e8c500-1a75-11ea-8abd-bcde92ac3d3b.png)

**Comment by biancadanforth** [comment]
Edit: I'm also happy to revert the commit and open a PR as I intended! Just let me know what you prefer.

@erikrose , I mentioned this to you in slack, but just for posterity, I accidentally pushed my [patch](https://github.com/erikrose/gecko-dev/commit/1b757129451284d9839df5920c78bc90a844e670) directly to the `smoot-demo` branch instead of opening a PR. Would you mind taking a look at it and letting me know here (or wherever you prefer) your thoughts? Sorry for the confusion...

Edit: Here's a gif of this change in action on walmart.com.
![smoot-geck-dev-8](https://user-images.githubusercontent.com/17437436/70582937-0f4a3f80-1b71-11ea-825a-6aa499cf51dc.gif)

**Comment by biancadanforth** [comment]
Closed by 1b75712; thanks Erik.
